---
name: CI
on:
  pull_request:
    branches:
      - main
      - 'v*'

env:
  MODULES: "./docker/... ./e2e/... ./mailbox/... ./tx/..."

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.work
          cache-dependency-path: '*/go.sum'
          check-latest: true

      - name: Test
        run: make test

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.work
          cache-dependency-path: '*/go.sum'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
          args: '--config=.golangci.yaml -v $MODULES'
