---
name: CI
on:
  pull_request:
    branches:
      - main
      - 'v*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Go and restore cached dependencies
        uses: ./.github/actions/setup-go

      - name: Test
        run: go test -v ./e2e/...

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
          args: '--config=.golangci.yaml -v ./tx/... ./e2e/...'